### PR TITLE
distribution management repositories losing authentication settings

### PR DESCRIPTION
**Pull request by notiriel**
By just creating a new MavenRepository, the authentication settings of the repositories get removed. The additional code reuses the existing repos before creating a new one without auth.

### CODE REVIEW

**Comment by talios** [comment]
Cheers for this - do you have an example project you could add as an IT test? Or adapt/copy the existing `src/it/distributionManagemetTile` test?

**Comment by notiriel** [comment]
adapting the src/it/distributionManagemetTile didn't work, since actual distribution is disabled. Also I didn't find a way to verify presence of authentication information from the log files (which is good from a security point of view). I therefore decided to write a gray box test to verify the functionality of the change.

**Comment by talios** [comment]
Cheers - that's merged.  I'll look at getting that released tomorrow.

**Comment by RobertTheBlair** [comment]
I've been seeing similar issues with distribution management authentication being lost. Sadly this fix did not address it for my case.  Started having problems since 2.37.   
The issue is deep in a company repo, so will take some time to make a clean example.
The workaround is to not use tiles to manage dependencyManagement settings. 

When I have time, I'll try making a simple reproduction.

**Comment by talios** [comment]
@RobertTheBlair doh! Yeh - I always use the `altDeploymentRepository` property version in our release tile (which I still need to add an example to the doc).

If you can find a reproducible case that would be excellent!

**Comment by RobertTheBlair** [comment]
@talios I lost track of this request for a few months, but got reminded about this today.  I have a workaround, putting the dependency management in all 150 pom files, or not upgrading tiles.  What is notable is that without adding this section, the only thing seeming to be missing from the attempt to distribute is the credentials.
`
    <distributionManagement>
        <repository>
            <id>xoom-maven-releases</id>
            <name>Xoom Releases Repository</name>
            <url>https://ourprivate-artifactory/maven-xoom-releases</url>
        </repository>
    </distributionManagement>
`

**Pull request merged**
