### PR TITLE
Get rid of legacy

### PR DESCRIPTION
**Pull request by cstamas**
Drop plexus and any related class (sans plexus-utils, is there to stay), switch from Plx components to JSR230 and drop plexus XML and replace with proper compoments/providers.

Tidy up some things as well.

### CODE REVIEW

**Comment by talios** [comment]
Looks like there's some conflicts there?

**Comment by cstamas** [comment]
Yes, as it was done against master :smile:  you were faster to merge other

**Comment by cstamas** [comment]
rebased

**Review by talios — APPROVED** [review]
Even better! Muchly appreciated.

**Comment by talios** [comment]
It's almost 1am - I should be sleeping - but I saw the PR just as I was finishing things up :)

**Comment by cstamas** [comment]
Important note: now that you use sisu-maven-plugin, you are bound to max Java11 (so your project compiler.target or compiler.release) as long this https://github.com/eclipse/sisu.inject/commit/4790d3e28987ee4c2472d576e544c07028a85f42 is not released. In short, Sisu will fail to scan Java 12+ bytecode, but I think you are fine on Java 8 level for now.

**Comment by talios** [comment]
I assume then, since the majority of the code here is Groovy that it's only generating Java 8 level byte-code (the IT tests run and pass under JDK 18/19).

That is something to keep in mind tho.

**Comment by talios** [comment]
*starts watching sisu.inject in any case*

**Comment by rvowles** [comment]
If this upped the minimum version of Maven, the docs need to be updated as well.

**Comment by talios** [comment]
Don't think it's upped the minimum - I do see we still have `<version>[3.3.9,)</version>` in the `pom.xml` but I don't think that's been valid as a "minimum" for a long time given we depend on `maven-core:3.8.4`.

Sadly, after releasing this morning I noticed it didn't actually work under 4.0.0-alpha2 - and have since added a pipeline run to run the build and IT tests under the alpha build (which indeed fails - but passes on the rest).

**Pull request merged**
