### PR TITLE
maven 3.3.9 compatibility

### LINKED ISSUE #63: Cannot use a plain version number when declaring a tile
using:

					<tiles>
						<tile>nz.co.xxxxxx:xxxxx-tile-common:1.1-SNAPSHOT</tile>
					</tiles>

fails as it is trying to get the xml file. You have to wrap it in a fixed version range.

### LINKED ISSUE #77: Consider restoring support for Apache Maven 3.3.9
Following the release of 2.11, as mentioned on #65 we broke support of the older ( 2 versions ago ) release of Apache Maven 3.3.9.

We could either - revert the aether changes, or just document the minimum requirement is now 3.5.1.

I'm more in favour of documenting the minimum version - and maybe handling that problem cleaner.

### PR DESCRIPTION
**Pull request by bvella**
Extracted from #84. Fixes #77.

### CODE REVIEW

**Comment by bvella** [comment]
I left a comment on #86 that it requires this to be merged as well for it to work. The classloading workd differently when the extension is loaded from .mvn/extensions.xml file and without these changes, it will fail. Do you need anything else for this merge request?

**Comment by talios** [comment]
@bvella I can't find it now, but I remember making a comment on one of the tickets about maybe making the build fail ( able to relax to a warning maybe ) if the reactor contains a tile, and you DON'T have `.mvn/extensions.xml` defined - we could do that as a new issue/merge/release tho.

**Comment by bvella** [comment]
I don't remember this comment. Referring to #91, the extension is really only useful if you have a tile in the reactor AND it is used by another maven project in the reactor. I will submit a separate pr with documentation update and a warning about this situation.

**Comment by talios** [comment]
@bvella I remember my suggestion ( can't remember where it was ) was to add that warning in code as well if those conditions are met - if you have a tile in the reactor, AND you use it, and we know it's not going to work as expected without `.mvn/extensions.xml` - maybe fail the build.

**Comment by talios** [comment]
Well that's released now - and breaks horribly on my projects :( Trust me not to test it on real world projects.

**Comment by bvella** [comment]
How is it breaking? The tests and its run funeral and I have been using these patches in a big real world project for about 2 months. Working both in command line maven and in intellij. Can you run maven with -X and post any exceptions?

**Comment by talios** [comment]
@bvella Looks to a combination of the fact we're not including tiles as dependencies ( even when there's no reactor, so kinda pointless ) and the fact we have `[1.2]` square-bracketed locked-down versions, somewhere in the chain we're including multiple instances of the same tile as a dependency with different versions ranges, which trigger unresolvable ranges.

**Comment by bvella** [comment]
If you can give me a more specific scenario that I can replicate, I will see if I can fix it. I don't use version ranges in my tile dependencies, so I did not encounter this problem. It might be worth adding an integration test for such a scenario as well.

**Pull request merged**
